### PR TITLE
Feature/gemify

### PR DESCRIPTION
**Pull request by troelskn**
I made some structural changes to this project, to make it easier to maintain and distribute.

- Project is now bundled up as a gem.
- There is a binary as the main entrypoint.
- There is a test suite.

### CODE REVIEW

**Comment by Dorian** [comment]
@troelskn I couldn't build the gem (e.g. `gem build scss_lint-auto_correct.gemspec`) and I couldn't run the gem with `ruby -ilib bin/scss-lint-auto-correct`.

(Making it a gem is pretty sweet, thanks)

**Comment by Dorian** [comment]
@troelskn I added you as a collaborator and pushed your PR to the gemify branch for now

**Comment by troelskn** [comment]
Okey - I'll have a look at fixing the build

**Comment by troelskn** [comment]
Done. And I've published v1.0.0

**Pull request merged**
